from fastapi import APIRouter
from app.schemas.request import ContentPayload, SessionInsightRequest
from app.schemas.response import AnalysisResponse, SessionInsightResponse
from app.services.classifier import classify
from app.services.session_analyzer import analyze_session

router = APIRouter(prefix="/analyze", tags=["analyze"])


@router.post("/live", response_model=AnalysisResponse)
async def analyze_live(payload: ContentPayload) -> AnalysisResponse:
    """
    Classify a content item detected by the extension in real time.
    Accepts the normalized ScrollSense payload and returns a classification.
    """
    return await classify(payload)


@router.post("/session", response_model=SessionInsightResponse)
async def analyze_session_endpoint(request: SessionInsightRequest) -> SessionInsightResponse:
    """
    Analyze a batch of classified history items from the current session.

    Returns aggregate metrics, a session label, 3 insights, and 1–3 recommendations.
    The summary is generated by Gemini if available, otherwise a canned template is used.
    The existing /live classification flow is not affected.
    """
    return await analyze_session(request.items)
